numbers = [2, 3, 4]

In [5]:
times2 = numbers * 2
print('List of numbers twice = ', times2)

List of numbers twice =  [2, 3, 4, 2, 3, 4]


This is some text.  I can even write TeX code and compile it here:

$$ y = \alpha + \beta*X_{i,t} + \varepsilon_{i,t} $$

It's a nice features.

# Built-in types
# Numeric


In [1]:
three = 3

In [2]:
three

3

In [3]:
type(three)

int

In [4]:
three = float(3)

In [5]:
three

3.0

In [6]:
type(three)

float

In [7]:
x = 2
y = 5
x + y

7

In [8]:
# multiplication
x * y

10

In [9]:
# absolute value
abs(y - x)

3

In [10]:
# powers
x ** y

32

## booleans

In [11]:
drop_out = False

In [12]:
drop_out

False

In [13]:
type(drop_out)

bool

In [14]:
# Test that false = 0
drop_out == 0

True

In [15]:
x * drop_out

0

In [16]:
drop_out2 = 0
type(drop_out2)

int

In [17]:
drop_out3 = bool(0)
type(drop_out3)

bool

## Sequences

# Strings

In [18]:
# a string is defined by single or double quotes
name = 'Jason'

In [19]:
name

'Jason'

In [20]:
type(name)

str

In [21]:
# reference items in a sequence through an index value
# INDEX VALUES START AT 0
print('First letter = ', name[0])

First letter =  J


In [22]:
# You can use a colon to return a slice from a sequence
# note returns index up to, but including that index on the right side of the colon
name[1:3]

'as'

In [23]:
# leave one side of colon blank to get all elements before/after colon
name[:3]

'Jas'

In [24]:
name[2:]

'son'

In [25]:
# to grab the last element of the sequence
name[-1]

'n'

In [26]:
name

'Jason'

In [27]:
name[:]

'Jason'

In [28]:
# addition of strings
name + " DeBacker"

'Jason DeBacker'

In [29]:
# multiplication
name * 2

'JasonJason'

In [30]:
name.upper()

'JASON'

In [31]:
name.lower()

'jason'

## Lists

Lists are ordered collections of objects.  These object can be of different types.  But usuallly a list contains similarly typed objects.

Lists are "mutable", which means they can change after they've been created.

In [32]:
# list are defined with square brackets
num_list = [1, 2, 3]
num_list

[1, 2, 3]

In [33]:
num_list[1]

2

In [36]:
num_list2 = [1, 2, 3, 2]
num_list2

[1, 2, 3, 2]

In [37]:
xyz = [4, 5, 6]

In [38]:
type(xyz)

list

In [39]:
xyz

[4, 5, 6]

In [40]:
string_list = ['A', 'B', 'C', 1, 2, 3]

In [41]:
string_list

['A', 'B', 'C', 1, 2, 3]

In [42]:
string_list[0]

'A'

In [43]:
string_list[-1]

3

In [45]:
xyz[:2]

[4, 5]

In [46]:
xyz

[4, 5, 6]

In [47]:
xyz[-1] = 99
xyz

[4, 5, 99]

In [48]:
# you can iterate over sequences like lists
for i in xyz:
    print(i)

4
5
99


In [49]:
# strings too
for i in name:
    print(i)

J
a
s
o
n


In [50]:
# operations with lists
# addition
num_list + xyz

[1, 2, 3, 4, 5, 99]

In [51]:
# reversing a list
num_list[::-1]

[3, 2, 1]

In [52]:
num_list

[1, 2, 3]

In [53]:
num_list.reverse()

In [54]:
num_list

[3, 2, 1]

In [58]:
num_list

[3, 1]

In [59]:
# remove an element with a particular value
num_list.remove(3)
num_list

[1]

In [60]:
xyz

[4, 5, 99]

In [61]:
del(xyz[0])
xyz

[5, 99]

## Tuples

Tuples are ordered collections of objects.  Tuples are immutable.  Tuples more often contain heterogenous types of objects.

In [65]:
# to define a tuple, use parentheses
num_tuple = (1, 2, 3)
num_tuple

(1, 2, 3)

In [66]:
num_tuple[0]

1

In [67]:
for item in num_tuple:
    print(item)

1
2
3


In [68]:
num_tuple + (4, 5)

(1, 2, 3, 4, 5)

In [69]:
num_tuple

(1, 2, 3)

In [70]:
num_tuple2 = num_tuple + (4, 5)

In [71]:
num_tuple2

(1, 2, 3, 4, 5)

In [72]:
del(num_tuple[1])

TypeError: 'tuple' object doesn't support item deletion

In [73]:
num_tuple.remove(2)

AttributeError: 'tuple' object has no attribute 'remove'

## Range

A range is a sequence of numbers.  they are immutable.  Often used in loops.

In [74]:
range(3)

range(0, 3)

In [76]:
for i in range(3):
    print(i)

0
1
2


In [77]:
for i in range(1, 5):
    print(i)

1
2
3
4


In [78]:
# can add a third argument - step size
for i in range(15, 10, -1):
    print(i)

15
14
13
12
11


## Sets

Sets are unordered collections of unique values.  They are mutable.  

Useful for membership testing, uniqueness tests.

In [80]:
# to define a set, use curly braces
num_set = {1, 2, 3}
num_set

{1, 2, 3}

In [81]:
num_set = { 1, 2, 3, 3, 4, 2}
num_set

{1, 2, 3, 4}

In [83]:
4 in num_set

True

In [84]:
5 in num_set

False

In [85]:
num_set.remove(2)
num_set

{1, 3, 4}

In [86]:
num_set = {5, 4, 1, 2}
num_set

{1, 2, 4, 5}

In [87]:
num_set[1]

TypeError: 'set' object does not support indexing

In [88]:
for i in num_set:
    print(i)

1
2
4
5


## Dictionaries

Dictionaries are collections of key, value pairs.  Key provide pointers to associated values.

Typically, keys are strings.  But they can be other types.

Dictionaries are valuable for mappings.

In [90]:
# dictionaries are defined in curly brackets with key value pairs lists
address_dict = {'street': 'Greene St.', 'number': 1014, 'city': 'Columbia', 'state': 'SC'}
address_dict

{'city': 'Columbia', 'number': 1014, 'state': 'SC', 'street': 'Greene St.'}

In [91]:
# reference an element with its key
address_dict['city']

'Columbia'

In [92]:
for v in address_dict.values():
    print('Value = ', v)

Value =  Greene St.
Value =  1014
Value =  Columbia
Value =  SC


In [93]:
address_dict.values()

dict_values(['Greene St.', 1014, 'Columbia', 'SC'])

In [94]:
address_dict.keys()

dict_keys(['street', 'number', 'city', 'state'])

In [95]:
for k in address_dict.keys():
    print('Key = ', k)

Key =  street
Key =  number
Key =  city
Key =  state


In [96]:
for k, v in address_dict.items():
    print('Key = ', k, ' Value = ', v)

Key =  street  Value =  Greene St.
Key =  number  Value =  1014
Key =  city  Value =  Columbia
Key =  state  Value =  SC


### NumPy

NumPy is a package that is fundamental to scientific computing.  It allows matrix operations and some other functionality.  Like Matlab for Python.

In [2]:
# import NumPy
import numpy as np

In [3]:
# define an array
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
A + A

array([[2, 4],
       [6, 8]])

In [5]:
# multiplication is element by element
A * A

array([[ 1,  4],
       [ 9, 16]])

In [101]:
# dot prodcut
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

In [102]:
np.kron(A, A)

array([[ 1,  2,  2,  4],
       [ 3,  4,  6,  8],
       [ 3,  6,  4,  8],
       [ 9, 12, 12, 16]])

## NumPy broadcasting

Two arrays will be broadcast together if they are the same size OR, for any two dimensions to compare, one of them is the same size and the other is of lenght one.  Dimensions are compared started with the last.

In [6]:
A

array([[1, 2],
       [3, 4]])

In [7]:
B = np.array([2, 5])

In [8]:
A * B

array([[ 2, 10],
       [ 6, 20]])

In [9]:
B.shape

(2,)

In [10]:
C = np.array([1, 2, 1])
C

array([1, 2, 1])

In [11]:
A * C

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

# NumPy and special arrays

In [12]:
np.ones(2)

array([ 1.,  1.])

In [13]:
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [14]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [15]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Reshaping arrays

In [16]:
A.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
D = np.tile(A, (1, 1, 4))

In [19]:
D

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]]])

In [20]:
D.shape

(1, 2, 8)

In [21]:
D = np.tile(A.reshape((2, 2, 1)), (1, 1, 4))

In [22]:
D.shape

(2, 2, 4)

## Pandas

Main object in Pandas is the "DataFrame" - a 2D object.  Does offer advanced indexing so can reprsent multidimensinoal data in 2D.

In [23]:
import pandas as pd

In [25]:
# create a dictionary with some data
data = {'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'], 'year': [2014, 2015, 2016, 2015, 2016],
       'wins': [6, 5, 5, 10, 8]}
data

{'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'],
 'wins': [6, 5, 5, 10, 8],
 'year': [2014, 2015, 2016, 2015, 2016]}

In [26]:
frame = pd.DataFrame(data)

In [27]:
frame

school  wins  year
0  Texas     6  2014
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015
4    UGA     8  2016

In [28]:
frame.columns

Index(['school', 'wins', 'year'], dtype='object')

In [29]:
# to to do the same thing
list(frame)

['school', 'wins', 'year']

In [31]:
# To reference a particular column
frame['wins']

0     6
1     5
2     5
3    10
4     8
Name: wins, dtype: int64

In [32]:
frame['Wins']

KeyError: 'Wins'

In [33]:
frame.wins

0     6
1     5
2     5
3    10
4     8
Name: wins, dtype: int64

In [34]:
frame.loc[0]

school    Texas
wins          6
year       2014
Name: 0, dtype: object

In [35]:
frame.loc[1:3]

school  wins  year
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015

In [36]:
frame.loc[0, 'school']

'Texas'

In [37]:
frame.groupby(['school'])['wins'].sum()

school
Texas    16
UGA      18
Name: wins, dtype: int64

In [38]:
frame.describe()

wins        year
count   5.000000     5.00000
mean    6.800000  2015.20000
std     2.167948     0.83666
min     5.000000  2014.00000
25%     5.000000  2015.00000
50%     6.000000  2015.00000
75%     8.000000  2016.00000
max    10.000000  2016.00000

In [40]:
frame['wins squared'] = frame['wins'] ** 2
frame

school  wins  year  wins squared
0  Texas     6  2014            36
1  Texas     5  2015            25
2  Texas     5  2016            25
3    UGA    10  2015           100
4    UGA     8  2016            64

In [41]:
# to peak at the first two rows of data
frame.head(n=2)

school  wins  year  wins squared
0  Texas     6  2014            36
1  Texas     5  2015            25

In [42]:
# renaming columns
frame.rename(columns={"wins": "Wins", "wins squared": "win sq"}, inplace=True)

In [43]:
frame

school  Wins  year  win sq
0  Texas     6  2014      36
1  Texas     5  2015      25
2  Texas     5  2016      25
3    UGA    10  2015     100
4    UGA     8  2016      64